// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebComputer.Data;

#nullable disable

namespace WebComputer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530144803_UpdateImage")]
    partial class UpdateImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebComputer.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Computers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Dell",
                            Description = "CPU: Core i7-13700H, RAM: 16GB DDR5, SSD: 1TB",
                            Image = "xps15.jpg",
                            Name = "Dell XPS 15 9530",
                            Price = 1850.50m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Description = "CPU: Apple M3 Pro, RAM: 18GB, SSD: 512GB",
                            Image = "macpro14.jpg",
                            Name = "MacBook Pro 14 M3",
                            Price = 1999.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Asus",
                            Description = "CPU: Core i9, RAM: 32GB, VGA: RTX 4070",
                            Image = "rogg16.jpg",
                            Name = "Asus ROG Strix G16",
                            Price = 1650.00m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            Brand = "HP",
                            Description = "CPU: Core i7, RAM: 16GB, Cảm ứng 2-in-1",
                            Image = "spectre14.jpg",
                            Name = "HP Spectre x360 14",
                            Price = 1450.00m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Lenovo",
                            Description = "Trọng lượng siêu nhẹ 1.1kg, Cực bền bỉ",
                            Image = "thinkpad.jpg",
                            Name = "Lenovo ThinkPad X1",
                            Price = 1700.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Acer",
                            Description = "VGA: RTX 3070 Ti, Màn hình 165Hz",
                            Image = "helios300.jpg",
                            Name = "Acer Predator Helios",
                            Price = 1550.00m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 7,
                            Brand = "MSI",
                            Description = "Thiết kế kim loại nguyên khối, RTX 4060",
                            Image = "stealth16.jpg",
                            Name = "MSI Stealth 16 Studio",
                            Price = 1800.00m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Dell",
                            Description = "Laptop văn phòng giá rẻ, Core i5 thế hệ 12",
                            Image = "inspiron15.jpg",
                            Name = "Dell Inspiron 15",
                            Price = 650.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Asus",
                            Description = "Màn hình OLED sắc nét, Ryzen 7",
                            Image = "asusvivobook14x.jpg",
                            Name = "Asus VivoBook 14X",
                            Price = 850.00m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Apple",
                            Description = "Pin 18 tiếng, Màn hình 15.3 inch",
                            Image = "macair15m2.jpg",
                            Name = "MacBook Air 15 M2",
                            Price = 1299.00m,
                            Quantity = 18
                        });
                });

            modelBuilder.Entity("WebComputer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Logitech",
                            Description = "Chuột công thái học cao cấp",
                            Image = "mxmaster3s.jpg",
                            Name = "Chuột Logitech MX Master 3S",
                            Price = 99.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Keychron",
                            Description = "Bàn phím cơ không dây TKL",
                            Image = "keychronk8pro1.jpg",
                            Name = "Bàn phím Keychron K8 Pro",
                            Price = 110.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dell",
                            Description = "Màn hình 27 inch 4K chuẩn màu đồ họa",
                            Image = "u2723qe.jpg",
                            Name = "Màn hình Dell U2723QE",
                            Price = 550.00m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Sony",
                            Description = "Tai nghe Over-ear chống ồn chủ động",
                            Image = "sonywh1000xm5.jpg",
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 349.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Samsung",
                            Description = "Tốc độ đọc 7450 MB/s",
                            Image = "SamsungSSD990PRO.jpg",
                            Name = "SSD Samsung 990 PRO 1TB",
                            Price = 129.50m,
                            Quantity = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
