// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebComputer.Data;

#nullable disable

namespace WebComputer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530100431_UpdateImageUrls")]
    partial class UpdateImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebComputer.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Computers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Dell",
                            Description = "CPU: Core i7-13700H, RAM: 16GB DDR5, SSD: 1TB",
                            Image = "https://m.media-amazon.com/images/I/71c5W9NxN5L._AC_SL1500_.jpg",
                            Name = "Dell XPS 15 9530",
                            Price = 1850.50m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Description = "CPU: Apple M3 Pro, RAM: 18GB, SSD: 512GB",
                            Image = "https://m.media-amazon.com/images/I/61jLiCovxVL._AC_SL1500_.jpg",
                            Name = "MacBook Pro 14 M3",
                            Price = 1999.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Asus",
                            Description = "CPU: Core i9, RAM: 32GB, VGA: RTX 4070",
                            Image = "https://m.media-amazon.com/images/I/71sF78D8cUL._AC_SL1500_.jpg",
                            Name = "Asus ROG Strix G16",
                            Price = 1650.00m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            Brand = "HP",
                            Description = "CPU: Core i7, RAM: 16GB, Cảm ứng 2-in-1",
                            Image = "https://m.media-amazon.com/images/I/71YV6xXhQKL._AC_SL1500_.jpg",
                            Name = "HP Spectre x360 14",
                            Price = 1450.00m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Lenovo",
                            Description = "Trọng lượng siêu nhẹ 1.1kg, Cực bền bỉ",
                            Image = "https://m.media-amazon.com/images/I/51rG-8qA0PL._AC_SL1500_.jpg",
                            Name = "Lenovo ThinkPad X1",
                            Price = 1700.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Acer",
                            Description = "VGA: RTX 3070 Ti, Màn hình 165Hz",
                            Image = "https://m.media-amazon.com/images/I/71NZiNWEsIL._AC_SL1500_.jpg",
                            Name = "Acer Predator Helios",
                            Price = 1550.00m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 7,
                            Brand = "MSI",
                            Description = "Thiết kế kim loại nguyên khối, RTX 4060",
                            Image = "https://m.media-amazon.com/images/I/71qG5wD5e-L._AC_SL1500_.jpg",
                            Name = "MSI Stealth 16 Studio",
                            Price = 1800.00m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Dell",
                            Description = "Laptop văn phòng giá rẻ, Core i5 thế hệ 12",
                            Image = "https://m.media-amazon.com/images/I/71WN-NpqBmL._AC_SL1500_.jpg",
                            Name = "Dell Inspiron 15",
                            Price = 650.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Asus",
                            Description = "Màn hình OLED sắc nét, Ryzen 7",
                            Image = "https://m.media-amazon.com/images/I/71q8Fk5P3lL._AC_SL1500_.jpg",
                            Name = "Asus VivoBook 14X",
                            Price = 850.00m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Apple",
                            Description = "Pin 18 tiếng, Màn hình 15.3 inch",
                            Image = "https://m.media-amazon.com/images/I/81Fm0tFikPL._AC_SL1500_.jpg",
                            Name = "MacBook Air 15 M2",
                            Price = 1299.00m,
                            Quantity = 18
                        });
                });

            modelBuilder.Entity("WebComputer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Logitech",
                            Description = "Chuột công thái học cao cấp",
                            Image = "https://m.media-amazon.com/images/I/61ni3t1ryQL._AC_SL1500_.jpg",
                            Name = "Chuột Logitech MX Master 3S",
                            Price = 99.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Keychron",
                            Description = "Bàn phím cơ không dây TKL",
                            Image = "https://m.media-amazon.com/images/I/61u+v9D77vL._AC_SL1500_.jpg",
                            Name = "Bàn phím Keychron K8 Pro",
                            Price = 110.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dell",
                            Description = "Màn hình 27 inch 4K chuẩn màu đồ họa",
                            Image = "https://m.media-amazon.com/images/I/81dG19+E0xL._AC_SL1500_.jpg",
                            Name = "Màn hình Dell U2723QE",
                            Price = 550.00m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Sony",
                            Description = "Tai nghe Over-ear chống ồn chủ động",
                            Image = "https://m.media-amazon.com/images/I/51aXvjzcukL._AC_SL1500_.jpg",
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 349.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Samsung",
                            Description = "Tốc độ đọc 7450 MB/s",
                            Image = "https://m.media-amazon.com/images/I/81fHmA9+kGL._AC_SL1500_.jpg",
                            Name = "SSD Samsung 990 PRO 1TB",
                            Price = 129.50m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Corsair",
                            Description = "DDR5 6000MHz",
                            Image = "https://m.media-amazon.com/images/I/61u9K5b1qDL._AC_SL1500_.jpg",
                            Name = "RAM Corsair Vengeance 32GB",
                            Price = 115.00m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 7,
                            Brand = "NVIDIA",
                            Description = "Card đồ họa 12GB GDDR6X",
                            Image = "https://m.media-amazon.com/images/I/717v3t0Lz3L._AC_SL1500_.jpg",
                            Name = "VGA RTX 4070 Ti",
                            Price = 799.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 8,
                            Brand = "NZXT",
                            Description = "Tản nhiệt nước AIO có màn LCD",
                            Image = "https://m.media-amazon.com/images/I/71G1f-jO0bL._AC_SL1500_.jpg",
                            Name = "Tản nhiệt NZXT Kraken 240",
                            Price = 139.00m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Shure",
                            Description = "Micro thu âm chuẩn Studio",
                            Image = "https://m.media-amazon.com/images/I/61zC4X++-KL._AC_SL1500_.jpg",
                            Name = "Micro Shure SM7B",
                            Price = 399.00m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 10,
                            Brand = "SteelSeries",
                            Description = "Lót chuột size L",
                            Image = "https://m.media-amazon.com/images/I/51wB7-7LhtL._AC_SL1500_.jpg",
                            Name = "Bàn di chuột SteelSeries",
                            Price = 15.00m,
                            Quantity = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
